#!/bin/bash

test_count=0
fail_count=0

ok() {
    echo OK
    test_count=$((${test_count} + 1))
}

fail() {
    exp="$1"
    got="$2"
    echo FAIL
    if [ -n "${exp}" -a -n "${got}" ]; then
        echo expected: ${exp}, got: ${got}
    fi
    test_count=$((${test_count} + 1))
    fail_count=$((${fail_count} + 1))
}

oosmake="$(pwd)/../oosmake"

for i in case-*; do
    echo -n "$i… "
    cd "$i"
    got=$(. prep && "${oosmake}")
    exp=$(echo -n $(readlink -f $(pwd)) && cat expect)
    if [ "${got}" == "${exp}" ]; then
        ok
    else
        fail "${exp}" "${got}"
    fi
    cd ..
done

echo -n '$(oosmake --version)… '
if "${oosmake}" --version >/dev/null 2>&1; then
    ok
else
    fail
fi

if [ 0 != ${fail_count} ]; then
    echo "*** ${fail_count} of ${test_count} tests failed"
    exit 1
fi

echo "ALL PASS"
