#!/bin/bash

fail=0

agmake="$(pwd)/../agmake"
for i in case-*; do
	echo -n "$i… "
	cd "$i"
	got=$(. prep && "${agmake}")
	exp=$(echo -n $(pwd) && cat expect)
	if [ "${got}" == "${exp}" ]; then
		echo OK
	else
		echo FAIL
        echo expected: ${exp}, got: ${got}
		fail=1
	fi
	cd ..
done

exit ${fail}

